openapi: 3.0.3
info:
  title: Steam Data API
  description: API para acceder y analizar datos de Steam
  version: '1'
servers:
  - url: https://proyecto-individual-dqlw.onrender.com
paths:
  /PlayTimeGenre/{genre}:
    get:
      summary: Tiempo de Juego por Género
      description: Obtener el año del género más jugado y el tiempo total de juego.
      parameters:
        - name: genre
          in: path
          description: El género del que se desea obtener información.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
  /UserForGenre/{genre}:
    get:
      summary: Usuario por Género
      description: Obtener al usuario con más tiempo de juego para un género específico.
      parameters:
        - name: genre
          in: path
          description: El género del que se desea obtener información.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
  /UsersRecommend/{year}:
    get:
      summary: Usuarios Recomiendan
      description: Obtener los 3 mejores juegos recomendados para un año específico.
      parameters:
        - name: year
          in: path
          description: El año del que se desean obtener juegos recomendados.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Respuesta exitosa
  /UsersNotRecommend/{year}:
    get:
      summary: Usuarios No Recomiendan
      description: Obtener los 3 juegos menos recomendados para un año específico.
      parameters:
        - name: year
          in: path
          description: El año del que se desean obtener juegos menos recomendados.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Respuesta exitosa
  /SentimentAnalysis/{year}:
    get:
      summary: Análisis de Sentimientos
      description: Analizar datos de sentimiento para un año específico.
      parameters:
        - name: year
          in: path
          description: El año para analizar el sentimiento.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Respuesta exitosa
  /RecommendedGames/{id}:
    get:
      summary: Juegos Recomendados
      description: Obtener 5 juegos similares al proporcionado por ID.
      parameters:
        - name: id
          in: path
          description: El ID del juego para encontrar juegos similares.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Respuesta exitosa
